#pragma once
#include "NativeGameplayTags.h"
#include "HAL/Platform.h"

namespace BlotGameplayTags
{
	BLOTGAME_API   UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_AbilityInputBlocked);

	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	BLOTGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
}
